-- AlterTable
ALTER TABLE "ProspectProfile" ADD COLUMN     "givingCapacity" DOUBLE PRECISION NOT NULL DEFAULT 0.00,
ADD COLUMN     "givingScore" TEXT NOT NULL DEFAULT 'U',
ADD COLUMN     "netWorth" DOUBLE PRECISION NOT NULL DEFAULT 0.00;
