name: Trigger auto deployment for pl-app-np

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/pl-app-np-AutoDeployTrigger-bbd794b9-48a7-4d81-82f6-e577f6b67479.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PLAPPNP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PLAPPNP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PLAPPNP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: prospectliveacr.azurecr.io
          registryUsername: ${{ secrets.PLAPPNP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PLAPPNP_REGISTRY_PASSWORD }}
          containerAppName: pl-app-np
          resourceGroup: fundraising-dev
          imageToBuild: prospectliveacr.azurecr.io/pl-app-np:${{ github.sha }}
          buildArguments: |
            AUTH_SECRET=${{ secrets.AUTH_SECRET }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            SEC_API_KEY=${{ secrets.SEC_API_KEY }}


